// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/transaction-event.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionType int32

const (
	TransactionType_TRANSACTION_TYPE_BET TransactionType = 0
	TransactionType_TRANSACTION_TYPE_WIN TransactionType = 1
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "TRANSACTION_TYPE_BET",
		1: "TRANSACTION_TYPE_WIN",
	}
	TransactionType_value = map[string]int32{
		"TRANSACTION_TYPE_BET": 0,
		"TRANSACTION_TYPE_WIN": 1,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_transaction_event_proto_enumTypes[0].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_api_transaction_event_proto_enumTypes[0]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_api_transaction_event_proto_rawDescGZIP(), []int{0}
}

type TransactionEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TransactionType TransactionType        `protobuf:"varint,2,opt,name=transaction_type,json=transactionType,proto3,enum=api.TransactionType" json:"transaction_type,omitempty"`
	Amount          float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransactionEvent) Reset() {
	*x = TransactionEvent{}
	mi := &file_api_transaction_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionEvent) ProtoMessage() {}

func (x *TransactionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_transaction_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionEvent.ProtoReflect.Descriptor instead.
func (*TransactionEvent) Descriptor() ([]byte, []int) {
	return file_api_transaction_event_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TransactionEvent) GetTransactionType() TransactionType {
	if x != nil {
		return x.TransactionType
	}
	return TransactionType_TRANSACTION_TYPE_BET
}

func (x *TransactionEvent) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_api_transaction_event_proto protoreflect.FileDescriptor

const file_api_transaction_event_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/transaction-event.proto\x12\x03api\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbe\x01\n" +
	"\x10TransactionEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12?\n" +
	"\x10transaction_type\x18\x02 \x01(\x0e2\x14.api.TransactionTypeR\x0ftransactionType\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp*E\n" +
	"\x0fTransactionType\x12\x18\n" +
	"\x14TRANSACTION_TYPE_BET\x10\x00\x12\x18\n" +
	"\x14TRANSACTION_TYPE_WIN\x10\x01B/Z-github.com/bsko/casino-transaction-system/apib\x06proto3"

var (
	file_api_transaction_event_proto_rawDescOnce sync.Once
	file_api_transaction_event_proto_rawDescData []byte
)

func file_api_transaction_event_proto_rawDescGZIP() []byte {
	file_api_transaction_event_proto_rawDescOnce.Do(func() {
		file_api_transaction_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_transaction_event_proto_rawDesc), len(file_api_transaction_event_proto_rawDesc)))
	})
	return file_api_transaction_event_proto_rawDescData
}

var file_api_transaction_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_transaction_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_transaction_event_proto_goTypes = []any{
	(TransactionType)(0),          // 0: api.TransactionType
	(*TransactionEvent)(nil),      // 1: api.TransactionEvent
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_api_transaction_event_proto_depIdxs = []int32{
	0, // 0: api.TransactionEvent.transaction_type:type_name -> api.TransactionType
	2, // 1: api.TransactionEvent.timestamp:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_transaction_event_proto_init() }
func file_api_transaction_event_proto_init() {
	if File_api_transaction_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_transaction_event_proto_rawDesc), len(file_api_transaction_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_transaction_event_proto_goTypes,
		DependencyIndexes: file_api_transaction_event_proto_depIdxs,
		EnumInfos:         file_api_transaction_event_proto_enumTypes,
		MessageInfos:      file_api_transaction_event_proto_msgTypes,
	}.Build()
	File_api_transaction_event_proto = out.File
	file_api_transaction_event_proto_goTypes = nil
	file_api_transaction_event_proto_depIdxs = nil
}
